version: '3.8'
services:
  app:
    build: .
    ports:
      - "7860:7860"  # Gradio по умолчанию использует порт 7860
    environment:
      - PORT=7860  # Важно для Render.com
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}  # Передаем API-ключ
